### ISSUE TITLE
Multiple JOSE implementations

### ISSUE THREAD

**Issue by kuba** [mpdavis/python-jose#1]
It seems like at the moment there are at least three different code bases implementing JOSE:
- this repo ([python-jose@pypi](https://pypi.python.org/pypi/python-jose/0.2.0))
- https://github.com/Demonware/jose ([jose@pypi](https://pypi.python.org/pypi/jose))
- I've baked my own solution for the [Let's Encrypt project](https://letsencrypt.org/) at https://github.com/letsencrypt/lets-encrypt-preview/tree/master/letsencrypt/acme/jose

Shall we start thinking about a unified solution? :)

cc: @mpdavis, @demianbrecht

**Comment by mpdavis** [comment]
I am certainly happy to look into a unified solution, but I use this library at work and we have a couple quirky requirements that stem from having to support Google App Engine, which we use fairly extensively. This mostly boils down to having to use PyCrypto instead of the cryptography library and being able to quickly update any security issues that crop up.

**Comment by mpdavis** [comment]
Another implementation: https://github.com/rohe/pyjwkest
