### ISSUE TITLE
JWE module missing

### ISSUE THREAD

**Issue by lelabo-marc** [mpdavis/python-jose#219]
OS:  Ubuntu 20.04.1 LTS
Env: Python 3.8

I tried to install the 4 configurations of `python-jose` , the `jwe` module is always missing.
I checked the source of the project, and its present in the source since 7 months.

Am I the only one in this case ?

**Comment by blag** [comment]
You are not the only one. I have not pushed a release to PyPI with those changes yet.

I have been exceptionally busy for the past few months, and I am the only active maintainer. If you would like to help out, please email mpdavis and ask to be added as a collaborator/maintainer on GitHub, RTD, and PyPI.

Closing, since this isn't really a bug.
