### ISSUE TITLE
JWTError

### ISSUE THREAD

**Issue by hmehran** [mpdavis/python-jose#25]
Hello I've been looking for how to use JWTError but i couldn't find an example anywhere. Did I miss it?

**Comment by mpdavis** [comment]
Is there a use case you are wanting to use them for?

`JWTError` is just a base error class that is used for all errors that the JWT api will throw.  This allows consumers to catch a single exception instead of a laundry list of errors thrown by each of the algorithm types.

```python
from jose import jwt
from jose.exceptions import JWTError

try:
    jwt.decode(token, 'secret', algorithms=['HS256'])
except JWTError as e:
    print "Something went wrong!"
```
In turn, `JWTError` is derived from `JOSEError` which is the base exception for all python-jose errors.
