### ISSUE TITLE
JWK example in documentation is wrong

### ISSUE THREAD

**Issue by bjmc** [mpdavis/python-jose#28]
The example [given here](http://python-jose.readthedocs.io/en/stable/jwk/index.html#examples) doesn't work:

`key.verify(token)`

raises an exception:

`*** TypeError: verify() takes exactly 3 arguments (2 given)`

**Comment by mpdavis** [comment]
It does appear that documentation is incorrect.  I [updated the documentation](http://python-jose.readthedocs.io/en/latest/jwk/index.html#examples) and tested that it is correct.

I had originally planned on implementing a simpler JWK API, especially when working with JWS objects, but it ended up being a rewrite of the JWS verification.  JWKs aren't required to be used only with JWS objects, so I don't know that it makes sense tailor that API specifically towards those objects.

If you are attempting to verify JWS/JWT objects instead of arbitrary strings, those APIs will accept a JWK dictionary directly and simplify things a bit.

```python
from jose import jws

token = "eyJhbGciOiJIUzI1NiIsImtpZCI6IjAxOGMwYWU1LTRkOWItNDcxYi1iZmQ2LWVlZjMxNGJjNzAzNyJ9.SXTigJlzIGEgZGFuZ2Vyb3VzIGJ1c2luZXNzLCBGcm9kbywgZ29pbmcgb3V0IHlvdXIgZG9vci4gWW91IHN0ZXAgb250byB0aGUgcm9hZCwgYW5kIGlmIHlvdSBkb24ndCBrZWVwIHlvdXIgZmVldCwgdGhlcmXigJlzIG5vIGtub3dpbmcgd2hlcmUgeW91IG1pZ2h0IGJlIHN3ZXB0IG9mZiB0by4.s0h6KThzkfBBBkLspW1h84VsJZFTsPPqMDA7g1Md7p0"

hmac_key = {
    "kty": "oct",
    "kid": "018c0ae5-4d9b-471b-bfd6-eef314bc7037"
    "use": "sig",
    "alg": "HS256",
    "k": "hJtXIZ2uSN5kbQfbtTNWbpdmhkV8FJG-Onbc6mxCcYg"
}

jws.verify(token, hmac_key, algorithms='HS256')
```

**Comment by bjmc** [comment]
Thanks for the quick response! That's a good tip, too.

What I'm actually trying to accomplish is verifying a Google `id_token` against [their list of signing keys](https://www.googleapis.com/oauth2/v3/certs), as [documented here.](https://developers.google.com/identity/protocols/OpenIDConnect#validatinganidtoken).

Would you be interested in adding functionality to `python-jose` so that the `key` argument to `jwt.decode()` could accept a list of keys in JWK dictionary format? Or perhaps a separate optional argument, `keys` instead of keys?

I think this is probably a common use-case, and if you're interested in supporting it, I can put together a pull request.

**Comment by mpdavis** [comment]
I think verifying against a number of keys would be a valid use case and I would gladly accept a PR.  Normally I would be able to take care of it over the weekend, but we had a storm take out a good portion of our fence so I will be working on that.

The only change I would make is accepting a JWK Set, which is part of [RFC 7517](https://tools.ietf.org/html/rfc7517#section-5).  I would be open to accepting a simple list of JWKs as well, which is just the value associated with the 'keys' parameter of the JWK Set.  I'll leave that up to you.

**Comment by bjmc** [comment]
I opened a couple pull requests relevant to my use-case.
