### ISSUE TITLE
pycrypto is default backend, but setup.py still requires pycryptodome

### ISSUE THREAD

**Issue by sfro** [mpdavis/python-jose#79]
In this commit python-jose defaults back to pycrypto:
https://github.com/mpdavis/python-jose/commit/402c815b7c9643896f66fe920f59ae6362088ca1

So latest master is like this:
https://github.com/mpdavis/python-jose/blob/master/jose/backends/__init__.py

Yet setup.py still requires pycryptodome in latest master:
https://github.com/mpdavis/python-jose/blob/master/setup.py

Is there a reason behind why pycryptodome is still required?

**Comment by mpdavis** [comment]
pycryptodome is the default now.

It is a bit wonky, but because the pycrypto and pycrpytodome use the same API, the pycrypto_backend is used for both of them.

In the pycrypto_backend, we default to using pycryptodome, unless pycrypto is installed.  https://github.com/mpdavis/python-jose/blob/master/jose/backends/pycrypto_backend.py#L18-L24

If you are wanting to use pycryptodome, but pycrypto is being used, uninstalling pycrypto should get it done.

**Comment by sfro** [comment]
So if we want to keep using pycrypto, pycryptodome is still required?

**Comment by mpdavis** [comment]
For now it is. I can probably work setup.py to pull that in a little better to avoid that, unfortunately there no way to set a "default" extras.

**Comment by sfro** [comment]
Ok, we are having trouble using the pycrypto library as both pycrypto and pycryptodome end up in "/lib/Crypto", not sure if we're the only ones :) there are some differences in string handling so they aren't 100% interchangeable. We might just bite the bullet and switch though.

**Comment by mpdavis** [comment]
Switching would be the recommended option, but pycrpyto should still be an option. There are places where pycryptodome isn't yet supported.

**Comment by mpdavis** [comment]
Pinning to 1.4.0 would also be an option.

**Comment by sfro** [comment]
Ok, we probably end up pinning it to 1.4.0 for the moment. Thanks for the explanation!

**Comment by evanj** [comment]
`pycryptodome` ships a package with a separate namespace as `pycryptodomex`; If this package depended on that instead, it might avoid this conflict. We run into this because we use `python-jose` on Google App Engine Standard, which supports `pycrypto` but no other native code libraries. For now I will attempt to pin to the old version to avoid this issue. Thanks!

**Comment by mpdavis** [comment]
This should be resolved in https://github.com/mpdavis/python-jose/releases/tag/3.0.0

We moved to the pure-python rsa module as a default backend, and custom backends have to be installed manually.
